name = "pet-keeping-api"
main = "src/worker.js"
compatibility_date = "2024-09-23"
account_id = "c1119e73537ab028455972057fa06376"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pet-keeping-db"
database_id = "04624bf2-2c6b-44b8-844f-bfde555ad8f2"
